[package]
name = "iyr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
content_inspector = "0.2.4"
crc32fast = "1.5.0"
infer = "0.19.0"
notify = "8.2.0"
notify-debouncer-full = "0.6.0"
